// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Automatically emails login credentials to management via Gmail after registration.
 *
 * - automateManagementCredentialDelivery - A function that sends the credentials.
 * - AutomateManagementCredentialDeliveryInput - The input type for the automateManagementCredentialDelivery function.
 * - AutomateManagementCredentialDeliveryOutput - The return type for the automateManagementCredentialDelivery function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutomateManagementCredentialDeliveryInputSchema = z.object({
  email: z.string().email().describe('The email address of the management user.'),
  password: z.string().describe('The generated password for the management user.'),
});
export type AutomateManagementCredentialDeliveryInput = z.infer<typeof AutomateManagementCredentialDeliveryInputSchema>;

const AutomateManagementCredentialDeliveryOutputSchema = z.object({
  success: z.boolean().describe('Indicates whether the email was sent successfully.'),
  message: z.string().describe('A message indicating the status of the email sending process.'),
});
export type AutomateManagementCredentialDeliveryOutput = z.infer<typeof AutomateManagementCredentialDeliveryOutputSchema>;

export async function automateManagementCredentialDelivery(
  input: AutomateManagementCredentialDeliveryInput
): Promise<AutomateManagementCredentialDeliveryOutput> {
  return automateManagementCredentialDeliveryFlow(input);
}

const sendCredentialsPrompt = ai.definePrompt({
  name: 'sendCredentialsPrompt',
  input: {schema: AutomateManagementCredentialDeliveryInputSchema},
  prompt: `You are responsible for sending login credentials to new management users.
  Compose an email to the following user with their credentials. Be professional and informative.

  Email: {{{email}}}
  Password: {{{password}}}

  Subject: AcademiaFlow Management Account Credentials`,
});


const automateManagementCredentialDeliveryFlow = ai.defineFlow(
  {
    name: 'automateManagementCredentialDeliveryFlow',
    inputSchema: AutomateManagementCredentialDeliveryInputSchema,
    outputSchema: AutomateManagementCredentialDeliveryOutputSchema,
  },
  async input => {
    try {
      const {text} = await sendCredentialsPrompt(input);

      // TODO: Implement actual email sending logic here using a secure email service.
      // This is a placeholder; replace with actual implementation.
      console.log('Generated email content:', text);
      console.log('Sending email to:', input.email);

      // Simulate successful email sending
      return {
        success: true,
        message: `Credentials sent successfully to ${input.email}. (Simulated)`, //Indicates if credentials were sent to email
      };
    } catch (error: any) {
      console.error('Failed to send credentials:', error);
      return {
        success: false,
        message: `Failed to send credentials to ${input.email}: ${error.message}`,
      };
    }
  }
);
